name: Build LaTeX PDF

on:
  push:
    branches: [ "main", "master" ]
  pull_request:

jobs:
  build-latex:
    runs-on: ubuntu-latest

    steps:
      - name: Repository auschecken
        uses: actions/checkout@v4

      - name: LaTeX bauen
        uses: xu-cheng/latex-action@v3
        with:
          root_file: sample-sigconf.tex
          latexmk_use_xelatex: false   # auf true setzen, falls XeLaTeX
          extra_system_packages: "inkscape" # optional
          args: -pdf -interaction=nonstopmode -halt-on-error

      - name: PDF als Artifact hochladen
        uses: actions/upload-artifact@v4
        with:
          name: latex-pdf
          path: sample-sigconf.pdf
